apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: teslo-shop
  name: teslo-shop-service
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: teslo-shop
  type: NodePort
status:
  loadBalancer: {}
