apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: teslo-shop
  name: teslo-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teslo-shop
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: teslo-shop
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/teslo-shop-backend/teslo-shop-app/teslo-shop-backend
        name: teslo-shop
#      imagePullSecrets:
#      - name: gcr-json-key  # Aquí agregas el nombre del Secret
        env:
        - name: APP_VERSION
          value: "1.1.0"
        - name: PORT
          value: "3000"
        - name: STAGE
          value: "dev"  #prod => Error de SSL
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: DB_HOST
              
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: DB_PORT

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PASSWORD

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: teslo-shop-secret
              key: JWT_SECRET      
status: {}
