steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/teslo-shop-backend/teslo-shop-app/teslo-shop-backend:$SHORT_SHA",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/teslo-shop-backend/teslo-shop-app/teslo-shop-backend:$SHORT_SHA"
      ]

images:
  - "us-central1-docker.pkg.dev/teslo-shop-backend/teslo-shop-app/teslo-shop-backend:$SHORT_SHA"

options:
  logging: 'CLOUD_LOGGING_ONLY'
