steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-west1-docker.pkg.dev/teslo-shop-backend/teslo-shop/teslo-shop-backend:$SHORT_SHA",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-west1-docker.pkg.dev/teslo-shop-backend/teslo-shop/teslo-shop-backend:$SHORT_SHA"
      ]

images:
  - "southamerica-west1-docker.pkg.dev/teslo-shop-backend/teslo-shop/teslo-shop-backend:$SHORT_SHA"

options:
  logging: 'CLOUD_LOGGING_ONLY'
