version: '3'

services:

  #****************************************#
  # * BDD  : Postgres                      #
  #****************************************#
  db:
    image: postgres:14.3
    restart: always
    container_name: teslodb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  #**********************************************************************#
  # * Teslo-shop  : Error en el contenedor por el uso de paquete bcrypt  #
  #**********************************************************************#
  teslo-shop:
    container_name: teslo-shop
    image: nruz176/nestjs-teslo-shop:latest
    restart: always
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start:dev"
    environment:
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      PORT: 3000
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - db
